version: "3.9"
services:
  app:
    build: .
    container_name: aspnet_app
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=ep-autumn-base-a8jyb42o-pooler.eastus2.azure.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_URVbxQ7Ef4Kl;SSL Mode=Require;Trust Server Certificate=true
